name: Publish package to NPM Packages
on:
  release:
    types: [published]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          
      - run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate    
      - run: yarn 
      - run: yarn build
      - run: yarn publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

